name: road2sbi
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - jupyterlab
  - ipykernel
  - streamlit
  - plotly
  - sbi
  - pytorch
  - pytest
  - pip
  - pip:
      - uv
      - streamlit-plotly-events
      - streamlit-drawable-canvas
